# Generated by Django 3.2 on 2022-08-30 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220829_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01, 'Укажите количество!')], verbose_name='Количество'),
        ),
    ]
